export const FETCH_OXYGEN_DONORS_REQUEST = 'FETCH_OXYGEN_DONORS_REQUEST'
export const FETCH_OXYGEN_DONORS_SUCCESS = 'FETCH_OXYGEN_DONORS_SUCCESS'
export const FETCH_OXYGEN_DONORS_FAILURE = 'FETCH_OXYGEN_DONORS_FAILURE'